---
# List of plays
-
  # Hosts: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: always

  # Vars: variables that will apply to the play, on all targets 

  # Tasks: the list of tasks that will be executed within 
  #        the play, this section can also be used for 
  #        pre and post tasks
  tasks:
    # from https://superuser.com/questions/1395954/ansible-playbook-to-determine-os-release
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    # Detect if we are running on a WSL2 environment
  - name: Set wsl2_environment fact default to false
    set_fact:
      wsl2_environment: false
  - name: Set wsl2_environment fact True
    set_fact:
      wsl2_environment: true
    when: ansible_kernel is search("microsoft-standard-WSL2")  
  # fix for .gnupg/ permissions when building custom images
  - name: Add fix for .gnupg/ permissions
    lineinfile:
      path: "/etc/bash.bashrc"
      line: "chmod 700 ~/.gnupg/"    
  - name: Add custom prompt to /etc/skel/.profile
    lineinfile:
      path: "/etc/skel/.profile"
      line: 'export PS1="\e[0;32m[\w]\$ \e[0m"'

  # Handlers: the list of handlers that are executed as a notify 
  #           key from a task

  # Roles: list of roles to be imported into the play
  roles:
  - role: irixjp.role_example_hello

# Add additional plays here (remember the list entry -)
# Be sure to use the same hosts and connection entries above
# addtional plays

- 
  # Install NodeJS Tools
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_node

  vars:
    node_version: "16.14.0"
    v_node_version: "v{{ node_version }}"
    npm_version: "8.3.1"
    npx_version: "8.3.1"
    yarn_version: "1.22.11"


  tasks:   # Test Node JS Tools versions
  - name: Get node version
    shell: node --version
    register: installed_node_version
  - name: Get npm version
    shell: npm --version
    register: installed_npm_version
  - name: Get npx installed version
    shell: npx --version
    register: installed_npx_version
  - name: Get yarn version
    shell: yarn --version
    register: installed_yarn_version    
  - name: Display node tool versions
    debug:
      msg: "Node = {{ installed_node_version.stdout }} | npm = {{ installed_npm_version.stdout }} | npx = {{ installed_npx_version.stdout }} | yarn = {{ installed_yarn_version.stdout }}"
  - name: Test node version
    fail:
      msg: "NodeJS Version Error: Expected {{ v_node_version }} | Found {{ installed_node_version.stdout }}"
    when: installed_node_version.stdout != v_node_version      
  - name: Test npm version
    fail:
      msg: "NPM Version Error: Expected {{ npm_version }} | Found {{ installed_npm_version.stdout }}"
    when: installed_npm_version.stdout != npm_version
  - name: Test npx version
    fail:
      msg: "NPX Version Error: Expected {{ npx_version }} | Found {{ installed_npx_version.stdout }}"
    when: installed_npx_version.stdout != npx_version
  - name: Test yarn version
    fail:
      msg: "Yarn Version Error: Expected {{ yarn_version }} | Found {{ installed_yarn_version.stdout }}"
    when: installed_yarn_version.stdout != yarn_version        

  roles:
  - role: grzegorznowak.nvm_node
    nvm_install_script_version: "0.39.1"  
    nvm_node_version: "{{ node_version }}"  
    nvm_install_globally:
    - name: yarn
      version: "{{ yarn_version }}"

-
  # install keychain, and git
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_utilities

  vars:
    git_version: "2.35.1"
    git_version_to_install: "1:{{ git_version }}-0ppa1~ubuntu20.04.1"
    keychain_version: "2.8.5"
    keychain_version_to_install: "{{ keychain_version }}-1"
    keychain_version_expected: "{{ keychain_version }}.."

  tasks:
  - name: Add git PPA
    shell: add-apt-repository ppa:git-core/ppa
  - name: Install git
    apt:
      name: "git={{ git_version_to_install }}"  
  - name: Install Keychain
    apt:
      name: "keychain={{ keychain_version_to_install }}"
      update_cache: yes
  - name: Get git version
    shell: git version | sed 's/[[:alpha:]|(|[:space:]]//g'
    register: installed_git_version
  - name: Get keychain version
    shell: 
      cmd: keychain -V 2> >(grep -i keychain) 2> >(sed 's/[[:alpha:]|(|[:space:]]//g') | fgrep '*' | sed 's/[*~://]//g'
      executable: /bin/bash
    register: installed_keychain_version
  - name: Display git and keychain versions
    debug:
      msg: "git = {{ installed_git_version.stdout }} | keychain = {{ installed_keychain_version.stdout }}"
  - name: Test git version
    fail:
      msg: "Git Version Error: Expected {{ git_version }} | Found {{ installed_git_version.stdout }}"
    when: installed_git_version.stdout != git_version  
  - name: Test keychain version
    fail:
      msg: "Keychain Version Error: Expected {{ keychain_version_expected }} | Found {{ installed_keychain_version.stdout }}"
    when: installed_keychain_version.stdout != keychain_version_expected    

-
  # install Pandoc & TexLive
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_generator_pandoc

  vars:
    pandoc_version: "2.17.0.1"
    texlive_version: "2019.20200218-1"
    texlive_version_expected: "pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)"

  tasks:
  - name: install TeX Live
    apt:
      name: "texlive={{ texlive_version }}"  
      update_cache: yes
  - name: Get pandoc version
    shell: pandoc --version | grep -m 1 -i pandoc | sed 's/[[:alpha:]|(|[:space:]]//g'
    register: installed_pandoc_version
  - name: Get TeX Live version  
    shell: latex --version | grep -i Tex -m 1 
    register: installed_texlive_version
  - name: Display pandoc and texlive versions
    debug:
      msg: "pandoc = {{ installed_pandoc_version.stdout }} | texlive = {{ installed_texlive_version.stdout }}"
  - name: Test pandoc version
    fail:
      msg: "Pandoc Version Error: Expected {{ pandoc_version }} | Found {{ installed_pandoc_version.stdout }}"
    when: installed_pandoc_version.stdout != pandoc_version    
  - name: Test texlive version
    fail:
      msg: "TeX Live Version Error: Expected {{ texlive_version_expected }} | Found {{ installed_texlive_version.stdout }}"
    when: installed_texlive_version.stdout != texlive_version_expected        

  roles:
  - role: andrewrothstein.pandoc
    pandoc_ver: "{{ pandoc_version }}"

-
  # install PlantUML
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_generator_plantuml

  vars:
    jre_version: 2:1.11-72
    jre_version_expected: openjdk 11.0.13 2021-10-19

  tasks:
  - name: Install JRE
    apt:
      name: "default-jre={{ jre_version }}"
      update_cache: yes
  - name: Get JRE Version
    shell: java --version | grep -m 1 -i openjdk
    register: installed_jre_version
  - name: Display JRE, GraphViz, and PlantUML versions
    debug:
      msg: "JRE = {{ installed_jre_version.stdout }} | graphviz = | plantuml ="


# Three dots indicate the end of a YAML document
...
